/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/lib')['Button']
    ACheckbox: typeof import('ant-design-vue/lib')['Checkbox']
    ADropdown: typeof import('ant-design-vue/lib')['Dropdown']
    AForm: typeof import('ant-design-vue/lib')['Form']
    AFormItem: typeof import('ant-design-vue/lib')['FormItem']
    AInput: typeof import('ant-design-vue/lib')['Input']
    AInputPassword: typeof import('ant-design-vue/lib')['InputPassword']
    AMenu: typeof import('ant-design-vue/lib')['Menu']
    AMenuDivider: typeof import('ant-design-vue/lib')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/lib')['MenuItem']
    AModal: typeof import('ant-design-vue/lib')['Modal']
    ARadio: typeof import('ant-design-vue/lib')['Radio']
    ARadioGroup: typeof import('ant-design-vue/lib')['RadioGroup']
    ASelect: typeof import('ant-design-vue/lib')['Select']
    ASpace: typeof import('ant-design-vue/lib')['Space']
    ATextarea: typeof import('ant-design-vue/lib')['Textarea']
    CaretDownOutlined: typeof import('@ant-design/icons-vue')['CaretDownOutlined']
    DownOutlined: typeof import('@ant-design/icons-vue')['DownOutlined']
    DownSquareOutlined: typeof import('@ant-design/icons-vue')['DownSquareOutlined']
    MenuItem: typeof import('./src/components/MenuItem/index.vue')['default']
    MinusCircleOutlined: typeof import('@ant-design/icons-vue')['MinusCircleOutlined']
    PlusOutlined: typeof import('@ant-design/icons-vue')['PlusOutlined']
    Rename: typeof import('./src/components/MenuItem/Rename.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WaterFall: typeof import('./src/components/WaterFall/index.vue')['default']
  }
}
