/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/lib')['Button']
    ADropdown: typeof import('ant-design-vue/lib')['Dropdown']
    AMenu: typeof import('ant-design-vue/lib')['Menu']
    AMenuItem: typeof import('ant-design-vue/lib')['MenuItem']
    MenuItem: typeof import('./src/components/MenuItem/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WaterFall: typeof import('./src/components/WaterFall/index.vue')['default']
  }
}
